use super::{cmd, cmd_json};

pub(super) fn extend(commands: &mut Vec<serde_json::Value>) {
    commands.extend([
        // ── 기계 계약(--json) 명령 ──
        cmd_json(
            "info",
            "문서 메타(포맷·버전·마지막 저장 제품·페이지/문단 수·폰트·제목) 표시",
            &["--json"],
            &[
                "schemaVersion",
                "source",
                "format",
                "sizeBytes",
                "version",
                "sections",
                "pageCount",
                "paraCount",
                "fonts",
                "title",
                "lastSavedWith",
                "warnings",
            ],
        ),
        cmd_json(
            "word-count",
            "문서 분량(구역·문단·글자·어절·쪽 수) — IR 본문만 센다",
            &["--json"],
            &[
                "schemaVersion",
                "source",
                "sectionCount",
                "paragraphCount",
                "charCount",
                "wordCount",
                "pageCount",
            ],
        ),
        cmd_json(
            "bookmarks",
            "문서 책갈피 목록 — 코어 get_bookmarks_native",
            &["--json"],
            &["schemaVersion", "source", "count", "bookmarks"],
        ),
        cmd_json(
            "header-footer",
            "구역 머리말/꼬리말 한 건 조회 — 코어 get_header_footer_native",
            &["--json"],
            &[
                "schemaVersion",
                "source",
                "section",
                "isHeader",
                "applyTo",
                "exists",
            ],
        ),
        cmd_json(
            "headers-footers",
            "문서 머리말/꼬리말 목록 — 코어 get_header_footer_list_native",
            &["--json"],
            &["schemaVersion", "source", "count", "headersFooters"],
        ),
        cmd_json(
            "charts",
            "문서 차트 목록 — 코어 list_charts_native",
            &["--json"],
            &["schemaVersion", "source", "count", "charts"],
        ),
        cmd_json(
            "form-value",
            "양식 개체 값 조회 — 코어 get_form_value_native",
            &["--section", "--para", "--ctrl", "--json"],
            &[
                "schemaVersion",
                "source",
                "section",
                "paragraph",
                "ctrl",
                "ok",
                "formType",
                "name",
                "value",
                "text",
                "caption",
                "enabled",
            ],
        ),
        cmd_json(
            "export-text",
            "페이지별 텍스트 추출 (TXT 파일 또는 --json stdout)",
            &["-o", "-p", "--max-chars", "--json"],
            &[
                "schemaVersion",
                "source",
                "pageCount",
                "truncated",
                "omittedCount",
                "pages",
            ],
        ),
        cmd_json(
            "export-structure",
            "문서 개요/조문 계층을 JSON 트리로 추출",
            &["--mode", "-o", "--json"],
            &["schemaVersion", "source", "mode", "nodeCount", "structure"],
        ),
        // [#3633] 초소형 모델용 매크로 1호 — info+structure+발췌를 원콜로 묶는다.
        // [#3633 후속] v2: --sections(주소 보존 절 청크)·--pages(범위 발췌) 추가.
        cmd_json(
            "digest",
            "문서 요약 봉투(메타·개요·발췌·nextStep)를 한 번 호출로 출력",
            &["--sections", "--pages", "--max-chars", "--json"],
            &[
                "schemaVersion",
                "source",
                "format",
                "pageCount",
                "paraCount",
                "outline",
                "excerpt",
                "sections",
                "truncated",
                "nextStep",
            ],
        ),
        cmd_json(
            "capabilities",
            "본 자기서술 JSON 출력",
            &["--search"],
            &[
                "schemaVersion",
                "schemaRegistry",
                "tool",
                "version",
                "exitCodes",
                "commands",
                "batch",
            ],
        ),
    ]);
}
